//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalSitter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listining
    {
        public int Id_list { get; set; }
        public string Name { get; set; }
        public int Id_user { get; set; }
        public int Experience { get; set; }
        public string Text { get; set; }
    
        public virtual User User { get; set; }
    }
}
